version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    hostname: app

    volumes:
      - ./app/static:/static
      - ./app/media:/media
      - ./app/logs:/logs
      - ./app:/code
    ports:
      - 8000:8000
    env_file:
      - env/app
    depends_on:
      - db
      - redis
    networks:
      - np-dev

  db:
    image: postgres:12.0
    hostname: db
    env_file:
      - env/db
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - np-dev

  redis:
    image: redis:6.0.9
    command: redis-server /volumes/redis/redis.conf
    hostname: redis
    env_file:
      - env/redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
      - ./redis.conf:/volumes/redis/redis.conf
    networks:
      - np-dev

  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    hostname: worker
    env_file:
      - env/worker
    volumes:
      - ./src:/code
      - ./volumes/logs:/logs
    depends_on:
      - redis
      - db
    networks:
      - np-dev

networks:
  np-dev:
    driver: bridge

